# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/milestone',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/milestone',
                'lib_path': 'milestone'},
  'syms': {'milestone.core': {'milestone.core.foo': ('core.html#foo', 'milestone/core.py')}}}
